# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c70c0f466cf74065b2db14c150ba7253eefc43715c4d6e3bb6d0b3a2910671c97d294b1aaa79e8e98d28200c0ba1b5ef0d7ef4baead69de90b912af3cb848c76

test:
  secret_key_base: e652b088009f09dd6e99fcdd734a2870b308f33b5450a2f602d3d94f18d637a5249c4f61f2cea3de5ee247ac3b66076eb94e6142e054272333429ae4ef1b4cdc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
